name: Clojure CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    - uses: DeLaGuardo/setup-clojure@3.1
      with:
        tools-deps: '1.10.1.469'
        # leiningen and boot-cli can be installed as well
        lein: 2.9.4
    - name: Run tests
      run: lein test
